// Static catalog data for the marketplace & wholesale sections.
// All user-facing strings (product names, brand names, shop names, supplier names,
// cities, badges) live in lib/i18n.tsx under `marketplace` and `wholesaleCatalog`.
// This file only holds the structural data (ids, categories, icons, visual tone,
// numeric prices / MOQ / ratings) so the same product can be referenced from
// multiple sections without duplicating copy.

import type { LucideIcon } from "lucide-react"
import {
  Glasses,
  Sun,
  Contact,
  Sparkles,
  Droplet,
  Eye,
} from "lucide-react"

export type Category = "eyeglasses" | "sunglasses" | "contacts"
export type ContactTone = "transparent" | "colored" | "cosmetic"

export type CustomerProduct = {
  id: string
  category: Category
  /** only meaningful for `contacts` */
  contactTone?: ContactTone
  /** product card background gradient stops */
  accent: { from: string; to: string }
  /** primary visual icon */
  icon: LucideIcon
  /** decorative secondary icon shown faintly behind */
  deco?: LucideIcon
  /** image url to show instead of icon if available */
  imageUrl?: string
  /** i18n key fragment used as `t.marketplace.products.<key>.name` etc. */
  key: string
  /** price in JOD */
  price: number
  rating: number
  /** badge key in `t.marketplace.badges` */
  badge?: "new" | "bestseller" | "limited"
}

export type WholesaleProduct = {
  id: string
  category: Category
  contactTone?: ContactTone
  accent: { from: string; to: string }
  icon: LucideIcon
  deco?: LucideIcon
  imageUrl?: string
  key: string
  /** wholesale unit price in JOD per piece / per box */
  unitPrice: number
  /** minimum order quantity (units or boxes) */
  moq: number
  /** number of tiers shown in the price ladder */
  tiers: number
  /** stock-on-hand indicator for the wholesale card */
  stock: number
}

export const customerProducts: CustomerProduct[] = [
  {
    id: "cl-gen-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Add-a-heading.webp",
    key: "prod_1",
    price: 25,
    rating: 4.8,
  },
  {
    id: "cl-gen-2",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/6-monthly.webp",
    key: "prod_2",
    price: 25,
    rating: 4.8,
  },
  {
    id: "cl-gen-3",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-2.webp",
    key: "prod_3",
    price: 5.5,
    rating: 4.8,
  },
  {
    id: "cl-gen-4",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-3.webp",
    key: "prod_4",
    price: 4,
    rating: 4.8,
  },
  {
    id: "cl-gen-5",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Add-a-heading.webp",
    key: "prod_5",
    price: 6,
    rating: 4.8,
  },
  {
    id: "cl-gen-6",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/6-monthly.webp",
    key: "prod_6",
    price: 7,
    rating: 4.8,
  },
  {
    id: "cl-gen-7",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-2.webp",
    key: "prod_7",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-8",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-3.webp",
    key: "prod_8",
    price: 4,
    rating: 4.8,
  },
  {
    id: "cl-gen-9",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-3.webp",
    key: "prod_9",
    price: 3,
    rating: 4.8,
  },
  {
    id: "cl-gen-10",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-5.webp",
    key: "prod_10",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-11",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-1.webp",
    key: "prod_11",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-12",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-1.webp",
    key: "prod_12",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-13",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-7.webp",
    key: "prod_13",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-14",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/dc7528cf-2163-4437-8bda-39def7ba6220.webp",
    key: "prod_14",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-15",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-55-1.webp",
    key: "prod_15",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-16",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-56.webp",
    key: "prod_16",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-17",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-55-1.webp",
    key: "prod_17",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-18",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-55.webp",
    key: "prod_18",
    price: 5,
    rating: 4.8,
  },
  {
    id: "cl-gen-19",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-57.webp",
    key: "prod_19",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-20",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-57-1.webp",
    key: "prod_20",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-21",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-57-2.webp",
    key: "prod_21",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-22",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/PHOTO-2024-10-21-21-25-57-3.webp",
    key: "prod_22",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-23",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/wild-Green-ONE-DAY-1-1.webp",
    key: "prod_23",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-24",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/vivid-grey-ONE-DAY-1-1.webp",
    key: "prod_24",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-25",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/stylish-hazel-1.webp",
    key: "prod_25",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-26",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/STYLISH-GREY1.webp",
    key: "prod_26",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-27",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/olive-green-2-300x300-1-1.webp",
    key: "prod_27",
    price: 20,
    rating: 4.8,
  },
  {
    id: "cl-gen-28",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/DEEP-BLUE-1.webp",
    key: "prod_28",
    price: 20,
    rating: 4.8,
  },
  {
    id: "cl-gen-29",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/basil-grey-300x300-1-1.webp",
    key: "prod_29",
    price: 20,
    rating: 4.8,
  },
  {
    id: "cl-gen-30",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Aqua-Grey-300x300-1-1.webp",
    key: "prod_30",
    price: 20,
    rating: 4.8,
  },
  {
    id: "cl-gen-31",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/TRI-GREY.webp",
    key: "prod_31",
    price: 20,
    rating: 4.8,
  },
  {
    id: "cl-gen-32",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/TRI-LIGHT-GREEN.webp",
    key: "prod_32",
    price: 20,
    rating: 4.8,
  },
  {
    id: "cl-gen-33",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/TRI-LIGHT-GREY.webp",
    key: "prod_33",
    price: 25,
    rating: 4.8,
  },
  {
    id: "cl-gen-34",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/TRI-LIGHT-BLUE.webp",
    key: "prod_34",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-35",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Tri-hazel-Adore-Tri-Collection.webp",
    key: "prod_35",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-36",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Adore-Trendy-Tri-Tone-lens-blue.webp",
    key: "prod_36",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-37",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/30-days-Biomedics-Copervision.avif",
    key: "prod_37",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-38",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/BFp34sI1f0ZxZsQ4LdrdyOpBm5Serag3z3VJXIqe.webp",
    key: "prod_38",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-39",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/4r5DMhya5TQHSeKHzluLSOeVdsiH8u014UF2gk75.webp",
    key: "prod_39",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-40",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/7T4xcXCa6BF9il6uxmj3hMKuwEytVtQbASdiQC4g.webp",
    key: "prod_40",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-41",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/gMliAiZyR17R1stuueXAUBUiX3jAXKNEzgmlpGf9.webp",
    key: "prod_41",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-42",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/3WxTu44ZrNuL69Q7sqH9mPzM2TJi2c8nlvjirz26.webp",
    key: "prod_42",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-43",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/fMMCWU2lQLdZrZBVyC4f7yemQGQZw9tSeCvimvc1.webp",
    key: "prod_43",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-44",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/rdrGMn6aeUM7iM683w50NgVxkADgZhyXgohMy5J0.webp",
    key: "prod_44",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-45",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Mps1ydOJU5EzXvHcRhtHQuRoCtIQkztsEb5dLHpS.webp",
    key: "prod_45",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-46",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Mm734DEY1VtcvapUMu50Nsgxao8QrmnRBQ8GcnLk.webp",
    key: "prod_46",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-47",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/JNBrXxpVVQwvBy5L2ef5wbymqdtVqIJujLntelDG.webp",
    key: "prod_47",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-48",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/dUiaVGsPPtNsYBQ84lD1OTyAH6EeT1IfPY7fXVsy.webp",
    key: "prod_48",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-49",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/IfxBQOwijE22gsSrTeD57phor4av3sP0i0rNltru.webp",
    key: "prod_49",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-50",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/6EuhlCF30vYRIqXWHYQnTHLuFMXApwc4uZsJvHdw.webp",
    key: "prod_50",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-51",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/VHGO4vzGLnmcM8V8wrm52wyoLwthn2hLRYR9CVVM.webp",
    key: "prod_51",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-52",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/0ru27q8kYvkR7eC7eYylbbqhiz30C8jMYplXGvAn.webp",
    key: "prod_52",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-53",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/tg555apXs6C3WJeuWpNuO7kMWC5EefxNXUWRafbr.webp",
    key: "prod_53",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-54",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/dnO4qHLQfWsIcZm7z9qpSOV9hTFDJzNNEzOVcpq4.webp",
    key: "prod_54",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-55",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/4LHbH1nobVDJxpuzFBt1S8emuoI4V1tmUJNa5NWR.webp",
    key: "prod_55",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-56",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/YSFM1mRtYJlki2U3EQwIBD0CSdqYff42hAjQrLJV.webp",
    key: "prod_56",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-57",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/0lhAYlBiWep1FA8WMbFrijWlOlY23rL8aqrRNeRs.webp",
    key: "prod_57",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-58",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/gU55KUhb7abxWycV44NoUHxjtWRSi43KJnuOWC8p.webp",
    key: "prod_58",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-59",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/dYLXwlkAdckc4lpSqT2puj1DrJ0VqLOPnHUbDVTm.webp",
    key: "prod_59",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-60",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Smr7Mby0BFKcBDKdzVfFLUTSOzqrpbRrYoBHNVma.webp",
    key: "prod_60",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-61",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/z7ZnJ2vIlLxKth1mjBfsLJ5qMDBLsHAjlYN0AKzG.webp",
    key: "prod_61",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-62",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/7647NYl7GpigL7xCVuDKsFtnSTMPblbQO9JVZvNc.webp",
    key: "prod_62",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-63",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/xno8kJ936IcEzBj6Ao7IvX6B0RebdaNk7CqfnjpG.webp",
    key: "prod_63",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-64",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/CZWaUVVzC6oJiPDrTUDGZyfllQDyzEqM37ycFqLP.webp",
    key: "prod_64",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-65",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/g1uzjmgzYH3xuGircDGpMohcUtVAxlER53wfQ6z4.webp",
    key: "prod_65",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-66",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/eQQxl2ZWnvbqhLqkg6Dwj7Jo0N8P2wAY5u9rV0w8.webp",
    key: "prod_66",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-67",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/uVTmcuN4Yo5UPt4qQH9dpd6XGuNel6mj437Pz3ZP.webp",
    key: "prod_67",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-68",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/mEjuWhmNl2VdyjymI9fgGxnisZHfp4OpLvWPVgIn.webp",
    key: "prod_68",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-gen-69",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/mSfrlTJHEmoZZ8J6C3CiTm2PQp3VCBBGi0FdGmbE.webp",
    key: "prod_69",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-70",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/V7z4dY0zGCRPJDIWXGdsYvBNGlQKrEJoy4oHMkFP.webp",
    key: "prod_70",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-71",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/qUoJSYxc8BYDAx4lHGBcwVUxCkE38aJ11cpXcyj1.webp",
    key: "prod_71",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-72",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/BKfatabEhbhFI5MvQSfVtwcFTjd26NRn1nnf58wh.webp",
    key: "prod_72",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-73",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/VN8OIUVLqWGjEIs5oxZaJWFCplRxNmHPKZa8zBdu.webp",
    key: "prod_73",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-74",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/CGYmlVPII3fSltf52j1clytTyjPYstuHRmzYUZjr.webp",
    key: "prod_74",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-75",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/bCPzh2V6cbY5lNqyWpW5zNvZkblH8yq65dZRMYxB.webp",
    key: "prod_75",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-76",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/zQKofcPmh3WHghQAyuRVLf2fyCA7RdlT1s8dhO0P.webp",
    key: "prod_76",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-77",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/NaunSdV4HTLb72WnoqqyO2WZdYUC3MliXRms0Mzh.webp",
    key: "prod_77",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-78",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/H5OHdDKFHBHCuQUet5I7MmsHv8XzP8Cj6NzGB0eA.webp",
    key: "prod_78",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-79",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/kIRFjB0k3zrr3OEjJZrrs1Qd2dEfziRB8ed4qgRC.webp",
    key: "prod_79",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-80",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Scwusg6ts25Fx2bbOK7r4EJNCyybBX6fmYq1pCx3.webp",
    key: "prod_80",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-81",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/bctrfMKBhCMs2u7ORYCaTeruf7xttDIdKJDtoF6i.webp",
    key: "prod_81",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-82",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Ootid7vlIkHVJrPOIv4bRtvjMtPJEQL9GEG9ORj5.webp",
    key: "prod_82",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-83",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/yTqCAlW20ugOZbhWMIl5Q6JEElqtbDzN3W3LFl85.webp",
    key: "prod_83",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-84",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Xqa1RmsZHKRXT1iGVV0G7Baj52dULvJnJuNSyxyd.webp",
    key: "prod_84",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-85",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/TwYb3wLIu5gEtf6rtRyu3BFC3WZtXeopwwsfpMVn.webp",
    key: "prod_85",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-86",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/FqYH0IRXpyRLtV4FUg6Acpe0vIDYcAiEsp4B0qtj.webp",
    key: "prod_86",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-87",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/9jqks5kW1RTizVHlTBuXy9rW3kMjMmhItxBHiUho.webp",
    key: "prod_87",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-88",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/xno8kJ936IcEzBj6Ao7IvX6B0RebdaNk7CqfnjpG.webp",
    key: "prod_88",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-89",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/kmfAw5gicNBghOQRgPQIhRMbenQiUVJptaFgIvvD.webp",
    key: "prod_89",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-90",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/GHGaXAneQRpHgFbJZ3ro0xPtJfQ0K38rp5fwtQfU.webp",
    key: "prod_90",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-91",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/JoleBKqUtWUqiiKbQEYZUuZHKpiTtgajRXZWCuUg.webp",
    key: "prod_91",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-92",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/uVTmcuN4Yo5UPt4qQH9dpd6XGuNel6mj437Pz3ZP.webp",
    key: "prod_92",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-93",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/ahTD5uD5wug6vBwNZJrkyFv3mJglqaL93t03zTzH.webp",
    key: "prod_93",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-94",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/fXmfJpq5OuEISSr5Ia9v7RgSEh8XnUo61whBTSWw.webp",
    key: "prod_94",
    price: 30,
    rating: 4.8,
  },
  {
    id: "cl-gen-95",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/wbiqaxaCAJUHZHTtpOCMOZYSfyZOiSl3lZsgmglm.webp",
    key: "prod_95",
    price: 25,
    rating: 4.8,
  },

  // ── Eyeglasses (5) ────────────────────────────────────────────────
  {
    id: "eg-1",
    category: "eyeglasses",
    accent: { from: "oklch(0.92 0.04 60)", to: "oklch(0.78 0.10 50)" },
    icon: Glasses,
    deco: Sparkles,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Add-a-heading.webp",
    key: "acetateRound",
    price: 29,
    rating: 4.8,
    badge: "bestseller",
  },
  {
    id: "eg-2",
    category: "eyeglasses",
    accent: { from: "oklch(0.88 0.02 240)", to: "oklch(0.62 0.04 235)" },
    icon: Glasses,
    deco: Sparkles,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/6-monthly.webp",
    key: "metalRectangle",
    price: 35,
    rating: 4.6,
  },
  {
    id: "eg-3",
    category: "eyeglasses",
    accent: { from: "oklch(0.85 0.08 80)", to: "oklch(0.55 0.13 65)" },
    icon: Glasses,
    deco: Eye,
    key: "catEyeTortoise",
    price: 42,
    rating: 4.9,
    badge: "new",
  },
  {
    id: "eg-4",
    category: "eyeglasses",
    accent: { from: "oklch(0.95 0.01 230)", to: "oklch(0.75 0.03 220)" },
    icon: Glasses,
    deco: Sparkles,
    key: "rimlessTitanium",
    price: 55,
    rating: 4.7,
    badge: "limited",
  },
  {
    id: "eg-5",
    category: "eyeglasses",
    accent: { from: "oklch(0.85 0.07 250)", to: "oklch(0.55 0.13 245)" },
    icon: Glasses,
    deco: Eye,
    key: "blueLight",
    price: 38,
    rating: 4.5,
  },

  // ── Sunglasses (5) ────────────────────────────────────────────────
  {
    id: "sg-1",
    category: "sunglasses",
    accent: { from: "oklch(0.30 0.04 250)", to: "oklch(0.18 0.03 235)" },
    icon: Sun,
    deco: Sparkles,
    key: "aviatorPolarized",
    price: 45,
    rating: 4.9,
    badge: "bestseller",
  },
  {
    id: "sg-2",
    category: "sunglasses",
    accent: { from: "oklch(0.22 0.02 60)", to: "oklch(0.12 0.01 50)" },
    icon: Sun,
    deco: Sparkles,
    key: "wayfarerClassic",
    price: 55,
    rating: 4.8,
  },
  {
    id: "sg-3",
    category: "sunglasses",
    accent: { from: "oklch(0.85 0.10 95)", to: "oklch(0.60 0.15 80)" },
    icon: Sun,
    deco: Eye,
    key: "roundVintage",
    price: 38,
    rating: 4.6,
  },
  {
    id: "sg-4",
    category: "sunglasses",
    accent: { from: "oklch(0.45 0.10 200)", to: "oklch(0.25 0.06 210)" },
    icon: Sun,
    deco: Sparkles,
    imageUrl: "https://jeepoo.com/wp-content/uploads/2025/02/Solution-1.webp",
    key: "sportWrap",
    price: 65,
    rating: 4.7,
    badge: "new",
  },
  {
    id: "sg-5",
    category: "sunglasses",
    accent: { from: "oklch(0.55 0.18 350)", to: "oklch(0.30 0.10 10)" },
    icon: Sun,
    deco: Sparkles,
    key: "catEyeFashion",
    price: 48,
    rating: 4.5,
    badge: "limited",
  },

  // ── Contact lenses (5) — mixed transparent & colored ────────────
  {
    id: "cl-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "dailyTransparent",
    price: 18,
    rating: 4.8,
    badge: "bestseller",
  },
  {
    id: "cl-2",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.93 0.03 200)", to: "oklch(0.76 0.06 195)" },
    icon: Contact,
    deco: Droplet,
    key: "monthlyTransparent",
    price: 25,
    rating: 4.7,
  },
  {
    id: "cl-3",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.78 0.13 245)", to: "oklch(0.45 0.16 250)" },
    icon: Contact,
    deco: Sparkles,
    key: "coloredSapphire",
    price: 22,
    rating: 4.9,
    badge: "new",
  },
  {
    id: "cl-4",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.80 0.16 150)", to: "oklch(0.48 0.17 155)" },
    icon: Contact,
    deco: Sparkles,
    key: "coloredEmerald",
    price: 22,
    rating: 4.8,
  },
  {
    id: "cl-5",
    category: "contacts",
    contactTone: "cosmetic",
    accent: { from: "oklch(0.82 0.12 75)", to: "oklch(0.55 0.16 70)" },
    icon: Contact,
    deco: Eye,
    key: "coloredHoney",
    price: 22,
    rating: 4.6,
  },
  {
    id: "cl-jj-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "jj30Daily",
    price: 25,
    rating: 4.8,
  },
  {
    id: "cl-jj-2",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "jj6Monthly",
    price: 25,
    rating: 4.8,
  },
  {
    id: "cl-dima-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Droplet,
    key: "dimaLenses100ml",
    price: 5.5,
    rating: 4.7,
  },
  {
    id: "cl-coper-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Droplet,
    key: "coperVision100ml",
    price: 4,
    rating: 4.8,
  },
  {
    id: "cl-avizor-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Droplet,
    key: "avizor350ml",
    price: 8,
    rating: 4.8,
  },
  {
    id: "cl-calavue-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.80 0.16 150)", to: "oklch(0.48 0.17 155)" },
    icon: Contact,
    deco: Sparkles,
    key: "calavueBrown",
    price: 5,
    rating: 4.6,
  },
  {
    id: "cl-celena-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.80 0.16 150)", to: "oklch(0.48 0.17 155)" },
    icon: Contact,
    deco: Sparkles,
    key: "celenaWildGreen",
    price: 8,
    rating: 4.7,
  },
  {
    id: "cl-adore-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.80 0.16 150)", to: "oklch(0.48 0.17 155)" },
    icon: Contact,
    deco: Sparkles,
    key: "adoreTriGrey",
    price: 20,
    rating: 4.9,
  },
  {
    id: "cl-biomedics-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.96 0.02 220)", to: "oklch(0.82 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "biomedics1Day",
    price: 25,
    rating: 4.9,
  },
]

export const wholesaleProducts: WholesaleProduct[] = [
  // ── Wholesale eyeglasses (5) ─────────────────────────────────────
  {
    id: "w-eg-1",
    category: "eyeglasses",
    accent: { from: "oklch(0.85 0.10 70)", to: "oklch(0.55 0.13 55)" },
    icon: Glasses,
    deco: Sparkles,
    key: "acetateRound",
    unitPrice: 12,
    moq: 50,
    tiers: 3,
    stock: 2400,
  },
  {
    id: "w-eg-2",
    category: "eyeglasses",
    accent: { from: "oklch(0.75 0.03 235)", to: "oklch(0.50 0.04 230)" },
    icon: Glasses,
    deco: Sparkles,
    key: "metalRectangle",
    unitPrice: 8,
    moq: 100,
    tiers: 4,
    stock: 5000,
  },
  {
    id: "w-eg-3",
    category: "eyeglasses",
    accent: { from: "oklch(0.80 0.12 75)", to: "oklch(0.50 0.16 65)" },
    icon: Glasses,
    deco: Eye,
    key: "catEyeTortoise",
    unitPrice: 14,
    moq: 50,
    tiers: 3,
    stock: 1800,
  },
  {
    id: "w-eg-4",
    category: "eyeglasses",
    accent: { from: "oklch(0.88 0.02 220)", to: "oklch(0.70 0.03 215)" },
    icon: Glasses,
    deco: Sparkles,
    key: "semiRimless",
    unitPrice: 10,
    moq: 75,
    tiers: 3,
    stock: 3200,
  },
  {
    id: "w-eg-5",
    category: "eyeglasses",
    accent: { from: "oklch(0.78 0.10 250)", to: "oklch(0.45 0.15 248)" },
    icon: Glasses,
    deco: Eye,
    key: "blueLightBulk",
    unitPrice: 9,
    moq: 100,
    tiers: 4,
    stock: 6000,
  },

  // ── Wholesale sunglasses (5) ─────────────────────────────────────
  {
    id: "w-sg-1",
    category: "sunglasses",
    accent: { from: "oklch(0.35 0.05 245)", to: "oklch(0.18 0.04 235)" },
    icon: Sun,
    deco: Sparkles,
    key: "aviatorPolarized",
    unitPrice: 18,
    moq: 80,
    tiers: 3,
    stock: 2800,
  },
  {
    id: "w-sg-2",
    category: "sunglasses",
    accent: { from: "oklch(0.25 0.03 55)", to: "oklch(0.12 0.02 50)" },
    icon: Sun,
    deco: Sparkles,
    key: "wayfarerClassic",
    unitPrice: 16,
    moq: 100,
    tiers: 4,
    stock: 4500,
  },
  {
    id: "w-sg-3",
    category: "sunglasses",
    accent: { from: "oklch(0.78 0.11 200)", to: "oklch(0.42 0.10 205)" },
    icon: Sun,
    deco: Sparkles,
    key: "sportWrap",
    unitPrice: 22,
    moq: 60,
    tiers: 3,
    stock: 1900,
  },
  {
    id: "w-sg-4",
    category: "sunglasses",
    accent: { from: "oklch(0.82 0.10 90)", to: "oklch(0.55 0.15 80)" },
    icon: Sun,
    deco: Eye,
    key: "roundMetalVintage",
    unitPrice: 19,
    moq: 50,
    tiers: 3,
    stock: 1500,
  },
  {
    id: "w-sg-5",
    category: "sunglasses",
    accent: { from: "oklch(0.55 0.18 350)", to: "oklch(0.30 0.10 10)" },
    icon: Sun,
    deco: Sparkles,
    key: "catEyeFashion",
    unitPrice: 17,
    moq: 70,
    tiers: 3,
    stock: 2100,
  },

  // ── Wholesale contact lenses (5) — transparent + colored ────────
  {
    id: "w-cl-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "dailyTransparent",
    unitPrice: 85,
    moq: 5,
    tiers: 3,
    stock: 1200,
  },
  {
    id: "w-cl-2",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.90 0.03 200)", to: "oklch(0.72 0.06 195)" },
    icon: Contact,
    deco: Droplet,
    key: "monthlyTransparent",
    unitPrice: 95,
    moq: 10,
    tiers: 3,
    stock: 800,
  },
  {
    id: "w-cl-3",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.75 0.14 248)", to: "oklch(0.42 0.17 252)" },
    icon: Contact,
    deco: Sparkles,
    key: "coloredSapphire",
    unitPrice: 110,
    moq: 5,
    tiers: 3,
    stock: 650,
  },
  {
    id: "w-cl-4",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.78 0.16 150)", to: "oklch(0.45 0.18 158)" },
    icon: Contact,
    deco: Sparkles,
    key: "coloredEmerald",
    unitPrice: 110,
    moq: 5,
    tiers: 3,
    stock: 720,
  },
  {
    id: "w-cl-5",
    category: "contacts",
    contactTone: "cosmetic",
    accent: { from: "oklch(0.80 0.13 75)", to: "oklch(0.50 0.17 68)" },
    icon: Contact,
    deco: Eye,
    key: "coloredHoney",
    unitPrice: 110,
    moq: 5,
    tiers: 3,
    stock: 580,
  },
  {
    id: "w-cl-jj-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "jj30Daily",
    unitPrice: 20,
    moq: 10,
    tiers: 3,
    stock: 500,
  },
  {
    id: "w-cl-jj-2",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "jj6Monthly",
    unitPrice: 20,
    moq: 10,
    tiers: 3,
    stock: 500,
  },
  {
    id: "w-cl-dima-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Droplet,
    key: "dimaLenses100ml",
    unitPrice: 4,
    moq: 20,
    tiers: 3,
    stock: 1500,
  },
  {
    id: "w-cl-coper-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Droplet,
    key: "coperVision100ml",
    unitPrice: 3,
    moq: 20,
    tiers: 3,
    stock: 2000,
  },
  {
    id: "w-cl-avizor-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Droplet,
    key: "avizor350ml",
    unitPrice: 6,
    moq: 20,
    tiers: 3,
    stock: 1200,
  },
  {
    id: "w-cl-calavue-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.78 0.16 150)", to: "oklch(0.45 0.18 158)" },
    icon: Contact,
    deco: Sparkles,
    key: "calavueBrown",
    unitPrice: 4,
    moq: 50,
    tiers: 3,
    stock: 1000,
  },
  {
    id: "w-cl-celena-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.78 0.16 150)", to: "oklch(0.45 0.18 158)" },
    icon: Contact,
    deco: Sparkles,
    key: "celenaWildGreen",
    unitPrice: 6,
    moq: 30,
    tiers: 3,
    stock: 800,
  },
  {
    id: "w-cl-adore-1",
    category: "contacts",
    contactTone: "colored",
    accent: { from: "oklch(0.78 0.16 150)", to: "oklch(0.45 0.18 158)" },
    icon: Contact,
    deco: Sparkles,
    key: "adoreTriGrey",
    unitPrice: 15,
    moq: 20,
    tiers: 3,
    stock: 400,
  },
  {
    id: "w-cl-biomedics-1",
    category: "contacts",
    contactTone: "transparent",
    accent: { from: "oklch(0.94 0.02 220)", to: "oklch(0.78 0.05 215)" },
    icon: Contact,
    deco: Droplet,
    key: "biomedics1Day",
    unitPrice: 20,
    moq: 10,
    tiers: 3,
    stock: 600,
  },
]

/** Used by the customer section to label products by tone. */
export const contactToneLabel: Record<ContactTone, "transparent" | "colored" | "cosmetic"> = {
  transparent: "transparent",
  colored: "colored",
  cosmetic: "cosmetic",
}